### ISSUE TITLE
Very cool user-interface demonstrating some of the ideas of tagging

### ISSUE THREAD

**Issue by arizvisa** [thalium/idatag#3]
Greetings Arnaud.

While surfing random things I came across your plugin which utilises tags and exposes them via a really neat user interface. This is super cool as I've been using my own tagging interface to do something incredibly similar in my own plugin, but with a sort of Python flavor to it since my goals were literally to serialize information outside of IDA and deserialize information back into IDA in a scalable manner. But.. similar to your plugin, I use it for sharing information between my debugger and my multiple IDBs which you seem to be using JSON for. 

The plugin I maintain is the ida-minsc plugin over at https://arizvisa.github.io/ida-minsc and I'm indexing tags in addresses, functions, function contents, and structures (indexing them inside a netnode, so that you can query them quickly.) As opposed to doing just selections with tags, I aimed to be able to store arbitrary Python types to allow for doing different types of querying, as well as sharing tags with other tools (similar to how you're using JSON for the exchange). An example of my tagging api is at https://arizvisa.github.io/ida-minsc/tutorials.html#tagging-all-dynamic-calls-in-the-database if you care). 

My "user-interface" essentially displays tags and their contents in comments since that's typically the way that I create them or view their contents....and more importantly because I didn't want to interfere too much with the already-existing user-interface for the sake of compatibility with older versions of IDA Pro. Anyways, my point of this "issue" is to ask your permission to leverage some of the user-interface ideas that you capture within your plugin? There wouldn't be any sharing of code due to your logic being in C++ and mine in Python, but I would definitely be translating your ideas into my plugin. Would that be okay?

If you prefer to talk over a different medium, I can also be reached at arizvisa@gmail.com. (feel free to close this issue either way).

**Comment by agatignol** [comment]
Hi Ali!

Thank you very much for your message.

Yes, I use JSON as a pivot between tools. The objective was to git them and to not depend on IDB files to store the analysis.

Of course, you can take everything you want in idatag! I would consider that as a good result for the project.
I might have somewhere a python version of the plugin, I can obviously also share it if it helps.
ida-minsc looks like a very good plugin and I will certainly try it out!

Again, thank you for this issue.

**Comment by arizvisa** [comment]
Awesome, man. I super-appreciate it and will credit your plugin. I'm currently working on adding wrappers around Hex-rays, but I think your idea is super cool since I guess people don't seem to recognize the usefulness of tags and yours pretty much highlights them. I've been using tags as sort of anchor points to share information from different tools, different users, or even different IDBs. Another thing I do is I index tags so that you can differentiate between things that you do and things that IDA does. This way you can do "cheap" tricks like allow IDA to apply public symbols, and then apply private symbols afterwards and then identify what was modified in the database. I also added support for tags to structures to allow you to share types that you've created between different databases, calculate offsets between fields, or to select basic-blocks that you're currently tracking. Kind of dumb things, but I've just found it useful over the years.

I haven't thought of exposing them via the ui because I also store Python values within them in a way that users can modify or tweak them (but the cost of building the initial Index is pretty expensive if you're dealing with a huge database). Did you write yours natively in C++ for performance reasons, or is that just how you've been maintaining it?

(edited: sorry for closing the issue, prematurely closed it)

**Comment by agatignol** [comment]
Hi!

> I've been using tags as sort of anchor points to share information from different tools, different users

This is a very cool feature! I have tried to put this information into the feeder properties (other tools, other user, etc.) of a tag. For instance, Tagcrypt (which is only findcrypt with tags): 

```
	{
		"tag": "SHA-1",
		"offset": 5065078,
		"feeder": "tagcrypt"
	}
```

> I also added support for tags to structures to allow you to share types

I had not this one! But clearly, I share the need :)

> I haven't thought of exposing them via the ui

This was the hard part for idatag. I thought that good ergonomy (through UI) was a reasonable objective but that was my slippery slope.

I wrote the C++ version only for performance reason during tag filtering (ctrl+f). But it seems that C++ is not enough if you have more than ten thousand tags : IDA still freezes (in the same manner than filtering the functions view in a big IDB).

**Comment by arizvisa** [comment]
> Hi!
> 
> > I've been using tags as sort of anchor points to share information from different tools, different users
> 
> This is a very cool feature! I have tried to put this information into the feeder properties (other tools, other user, etc.) of a tag. For instance, Tagcrypt (which is only findcrypt with tags):
> 
> ```
> 	{
> 		"tag": "SHA-1",
> 		"offset": 5065078,
> 		"feeder": "tagcrypt"
> 	}
> ```

Yeah, that's super cool that you've pretty much come to the same conclusion. :) I've actually always thought that tagging was a better solution with regards to collaborative reverse-engineering, even. There's been a large number of plugins over the years for collaborative reversing...and now we have "IDA Teams" to merge database changes between users, but I definitely still believe that tags are actually a better solution rather than just synchronizing database changes between different instances of IDA. Ideally, each user (or each tool) would be associated with a tag,,,pretty much __exactly__ like how you wrote it in your plugin. This way the users of a database should be able to "subscribe" to the tags that are relevant to their current reversing session... and, just like your idatags plugin, you'd be able to toggle the viewing of particular tags that come from different users or different tools.

I think this would change things so that using the database is more like collaborative editing of a "shared google doc" (with each tag point being a place where you could add reviews, sort of like https://www.youtube.com/watch?v=nbSmKACdfzM). Then from the tags each user could add comments and notations, or use another tool to generate different tags.

My implementation of tags doesn't take it this far or anything (since unfortunately I seldom reverse-engineer collaboratively). As such, my tagging implementation only aims to allow you to render user-defined tags (i.e. `"feeder": "tagcrypt"`) along with IDA's attributes with something I call an "implicit tag".

```
Python>db.tag(db.imports.search('*alloc*'))
WARNING:root:database.imports.search(fullname='*alloc*') : Found 8 matching results. Returning the first import "ole32!CoGetMalloc".
{'synopsis': "CoGetMalloc...'nuff said.", '__name__': 'CoGetMalloc', '__typeinfo__': 'HRESULT (__stdcall *CoGetMalloc)(DWORD dwMemContext, LPMALLOC *ppMalloc)'}
Python>func.tag()
{'jsvda_58.internal': 0x2780beb4, '__typeinfo__': 'int __cdecl sub_278097B6(void *ap_0, int av_size_4, char *)'}
```
In this, `__typeinfo__` is an implicit tag. So the idea is if you copy this tag value around, it will actually modify the database on your behalf. This then allows you to share information between databases (names, types, colors, comments) by simply copying them as text. Ideally, multiple users/tools will write tag values to the same database so that they can be used to select any number of things that may be relevant in their current project/session.

> > I also added support for tags to structures to allow you to share types
> 
> I had not this one! But clearly, I share the need :)

To do this, I ended up having to wrap the structure types in order to be able to "pickle" them with Python so that way you can "unpickle" them in the database that you want. What I've really found it useful for, though, has been to select certain fields to deference pointers (or whatever I'm trying to do) when debugging, or when copying type information from a function to a structure field for building vftables.

As an example, a quick function to generate windbg script for dereferencing fields within a structure can be something like:
```
import structure
def select(currenstruc, *args, **tags):
    '''recursively yield paths to any members that have been tagged'''
    for mem, t in currentstruc.select(*args, **tags):
        if not structure.has(mem.typeinfo):
            continue
        # yield current member
        yield [mem]
        # descend into member's structure
        memstruc = structure.by(mem.typeinfo)
        for children in select(memstruc, *args, **tags):
            yield [mem] + children
        continue
    return

def toexpr(members, start='poi(@esp+0x48)'):
    '''generate a windbg script'''
    expr = start
    for member in members:
        expr = 'poi(%s+%#x)'% (expr, member.offset)
    return expr
```

Which'll output something like the following if I tag the relevant fields that i want to dereference with "`the_fields_i_care_about`" and "`pointer`".
```
Python>for p in select(struc.by('union_68282'), And=['the_fields_i_care_about', 'pointer']):
Python> print('.'.join(x.name for x in p), toexpr(p))
Python>
p_localscope_0 poi(poi(@esp+0x48)+0x0)
p_localscope_0.v_data_4 poi(poi(poi(@esp+0x48)+0x0)+0x4)
p_localscope_0.v_data_4.p_object_0 poi(poi(poi(poi(@esp+0x48)+0x0)+0x4)+0x0)
p_localscope_0.v_data_4.p_object_30 poi(poi(poi(poi(@esp+0x48)+0x0)+0x4)+0x30)
...
p_localscope_0.v_data_4.p_streamInfoObject_a8.p_object_14.p_OleTable_20.p_iStorage_4 poi(poi(poi(poi(poi(poi(poi(@esp+0x48)+0x0)+0x4)+0xa8)+0x14)+0x20)+0x4)
```

Since Python is everywhere, I've been using tags to automate some aspects of debugging like this. I've also been using tags to save the contents of my database inside a `git` repository similar to the way that you can export and rebase them in your "idatag" plugin. But I'm sure there's other interesting things that can be done here that I haven't thought about yet. ;-)

> > I haven't thought of exposing them via the ui
> 
> This was the hard part for idatag. I thought that good ergonomy (through UI) was a reasonable objective but that was my slippery slope.
> 
> I wrote the C++ version only for performance reason during tag filtering (ctrl+f). But it seems that C++ is not enough if you have more than ten thousand tags : IDA still freezes (in the same manner than filtering the functions view in a big IDB).

Ah, wow. I was really hoping that wasn't the case. :-/ It could be because of IDA's view sorting is terrible, right?

After seeing your plugin also utilize tags, I was considering rewriting my tagging backend in native C++ for similar performance reasons. What I'm doing in my plugin is to literally hook the changes the user makes to the database in order to determine whether I add the location to the tag index (which in your plugin you're importing from JSON).

My hooking process is actually pretty slow __during__ the build of the database, so I try to track which state IDA is in before I scan the database to build my tag index. After the database has been built and the tag index is made, that's when I enable my hooks to track the changes that the user is making. If I have to work with a large binary, I work around the performance issue by building the idb ahead of time for a specific target.
